### PR TITLE
1.2

### PR DESCRIPTION
**Pull request by doutriaux1**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@chrisburr sorry to bother you. But I cant seemto be able to trigger the builds at this point. Any idea?

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
Making changes that affect the CI requires that that feedstock is "rerendered" (i.e. regenerate all the files outside the `recipe/` directory). Exactly when a re-render is required can be a little complicated so if in doubt, ask the bots to rerender 😃

**Comment by doutriaux1** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
